config/routes.rb
Rails.application.routes.draw do

  resources :sensor_values
  resources :regions
  resources :sensors do
       resources :sensor_values
  end
  resources :regions do
       resources :sensors
  end
  
  post '/register' => 'sensor_values#register', via: [:post], defaults: { format: :json }
  get '/charts' => 'sensor_values#charts', via: [:get]
  

end

app/models/region.rb
class Region < ActiveRecord::Base
    has_many :sensors
end
 

app/models/sensor.rb
class Sensor < ActiveRecord::Base
    has_many :sensor_value
    belongs_to :region
end

app/models/sensor_value.rb
class SensorValue < ActiveRecord::Base
    belongs_to :sensor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  # GET /regions
  # GET /regions.json
  def index
    @regions = Region.all
  end

  # GET /regions/1
  # GET /regions/1.json
  def show
    
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions
  # POST /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        sensor = Sensor.new
        sensor.name = 'AISUSAHIHSA'
        sensor.save # adding save here
        
        sensor1 = Sensor.new
        sensor1.name = '22222'
        sensor1.save # adding save here
        
        format.html { redirect_to @region, notice: 'Region was successfully created.' }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1
  # PATCH/PUT /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: 'Region was successfully updated.' }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url, notice: 'Region was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def region_params
      params.require(:region).permit(:name, :lat, :lng)
    end
end

app/controllers/sensor_values_controller.rb
class SensorValuesController < ApplicationController
  #before_action :set_region, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /regions
  # GET /regions.json
  def index
    zoom = params['zoom']
    number_of_entries = session['number_of_entries'] || 300
    if zoom
      if zoom == 'in'
        number_of_entries -= 100
      else
        number_of_entries += 100
      end
    end

    # we are using at least 300 entries as default
    if number_of_entries < 300
      number_of_entries = 300
    end
    session['number_of_entries'] = number_of_entries

    @sensor_values = SensorValue.all.includes(:sensor)
                                    .order(:date)
                                    .last(number_of_entries)
    
    resources = {}
    @sensor_values.each do |data|
      resource = resources[data.sensor.name] || {}
      
      resource['sensor_name'] = data.sensor.name
      resource['lat'] = data.sensor.region.lat
      resource['lng'] = data.sensor.region.lng
      
      value = {}
      value['value'] = data.value
      value['date'] = data.date

      values = resource['values'] || []
      values << value
      resource['values'] = values

      resources[data.sensor.name] = resource
    end
    
    render json: { resources: resources.values }
  end

  # GET /regions/1
  # GET /regions/1.json
  def show
  end

  def charts
  end

  def register
    data = sensor_params
    @region = Region.find_by_name(data[:region_name])
    @sensor = Sensor.find_by_name(data[:sensor_name])
    
    if not @region
      @region = Region.new
      @region.name = data[:region_name]
      @region.lat = data[:region_lat]
      @region.lng = data[:region_lng]
      @region.save # adding save here
    end
    
    if not @sensor
      @sensor = Sensor.new
      @sensor.name = data[:sensor_name]
      @sensor.save # adding save here
    end 
    
    @sensor.region = @region
    @sensor.save
    
    
    @sensorvalue = SensorValue.new
    @sensorvalue.value = data[:value]
    @sensorvalue.date = DateTime.parse(data[:date])
    @sensorvalue.sensor = @sensor
    @sensorvalue.save # adding save here    
    
    
    render json: { status: :ok }
  end

  # GET /regions/new
  def new
    @sensor_value = SensorValue.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_params
      params.require(:sensor_value).permit(:value, :sensor_name, :region_name,
                                           :region_lat, :region_lng, :date)
    end
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :set_sensor, only: [:show, :edit, :update, :destroy]

  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = Sensor.all
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
    
  end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(sensor_params)

    respond_to do |format|
      if @sensor.save
        sensor_value = SensorValue.new
        sensor_value.value = 67.8
        sensor_value.save # adding save here
        
        @sensor.sensor_value << sensor_value
        @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor was successfully created.' }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1
  # PATCH/PUT /sensors/1.json
  def update
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to @sensor, notice: 'Sensor was successfully updated.' }
        format.json { render :show, status: :ok, location: @sensor }
      else
        format.html { render :edit }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to sensors_url, notice: 'Sensor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_params
      params.require(:sensor).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/sensor_values_helper.rb
module SensorValuesHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EBillbreaker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <script type="text/javascript">
    google.load("visualization", "1", {packages:["line"]});
  </script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/regions/_form.html.erb
<%= form_for(@region) do |f| %>
  <% if @region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@region.errors.count, "error") %> prohibited this region from being saved:</h2>

      <ul>
      <% @region.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.text_field :lng %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/regions/edit.html.erb
<h1>Editing Region</h1>

<%= render 'form' %>

<%= link_to 'Show', @region %> |
<%= link_to 'Back', regions_path %>

app/views/regions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Regions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lat</th>
      <th>Lng</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @regions.each do |region| %>
      <tr>
        <td><%= region.name %></td>
        <td><%= region.lat %></td>
        <td><%= region.lng %></td>
        <td><%= link_to 'Show', region %></td>
        <td><%= link_to 'Edit', edit_region_path(region) %></td>
        <td><%= link_to 'Destroy', region, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Region', new_region_path %>

app/views/regions/new.html.erb
<h1>New Region</h1>

<%= render 'form' %>

<%= link_to 'Back', regions_path %>

app/views/regions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @region.name %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @region.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @region.lng %>
</p>

<%= link_to 'Edit', edit_region_path(@region) %> |
<%= link_to 'Back', regions_path %>

app/views/sensor_values/_form.html.erb
<%= form_for(@sensor_value) do |f| %>
  <% if @sensor_value.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sensor_value.errors.count, "error") %> prohibited this sensor_value from being saved:</h2>

      <ul>
      <% @sensor_value.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sensor_values/charts.html.erb
<p id="notice"><%= notice %></p>

<h1>e-BillBreaker</h1>
<button id='in'>Zoom In</button>
<button id='out'>Zoom Out</button>

<div id="chart_div"></div>

app/views/sensor_values/edit.html.erb
<h1>Editing Sensor Value</h1>

<%= render 'form' %>

<%= link_to 'Show', @sensor_value %> |
<%= link_to 'Back', sensor_values_path %>

app/views/sensor_values/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sensor Values</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sensor_values.each do |sensor_value| %>
      <tr>
        <td><%= sensor_value.value %></td>
        <td><%= sensor_value.sensor.name %></td>
        <td><%= link_to 'Show', sensor_value %></td>
        <td><%= link_to 'Edit', edit_sensor_value_path(sensor_value) %></td>
        <td><%= link_to 'Destroy', sensor_value, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sensor value', new_sensor_value_path %>

app/views/sensor_values/new.html.erb
<h1>New Sensor Value</h1>

<%= render 'form' %>

<%= link_to 'Back', sensor_values_path %>

app/views/sensor_values/show.html.erb
<html>
  <head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('number', 'x');
        data.addColumn('number', 'values');
        data.addColumn({id:'i0', type:'number', role:'interval'});
        data.addColumn({id:'i1', type:'number', role:'interval'});
        data.addColumn({id:'i2', type:'number', role:'interval'});
        data.addColumn({id:'i2', type:'number', role:'interval'});
        data.addColumn({id:'i2', type:'number', role:'interval'});
        data.addColumn({id:'i2', type:'number', role:'interval'});
  
        data.addRows([
            [1, 100, 90, 110, 85, 96, 104, 120],
            [2, 120, 95, 130, 90, 113, 124, 140],
            [3, 130, 105, 140, 100, 117, 133, 139],
            [4, 90, 85, 95, 85, 88, 92, 95],
            [5, 70, 74, 63, 67, 69, 70, 72],
            [6, 30, 39, 22, 21, 28, 34, 40],
            [7, 80, 77, 83, 70, 77, 85, 90],
            [8, 100, 90, 110, 85, 95, 102, 110]]);
  
        // The intervals data as narrow lines (useful for showing raw source data)
        var options_lines = {
            title: 'Line intervals, default',
            curveType: 'function',
            lineWidth: 4,
            intervals: { 'style':'line' },
            legend: 'none'
        };
  
        var chart_lines = new google.visualization.LineChart(document.getElementById('chart_lines'));
        chart_lines.draw(data, options_lines);
      }
    </script>
  </head>
  <body>
    <div id="chart_lines" style="width: 900px; height: 500px;"></div>
  </body>
</html>

app/views/sensors/_form.html.erb
<%= form_for(@sensor) do |f| %>
  <% if @sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
      <% @sensor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sensors/edit.html.erb
<h1>Editing Sensor</h1>

<%= render 'form' %>

<%= link_to 'Show', @sensor %> |
<%= link_to 'Back', sensors_path %>

app/views/sensors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sensors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sensors.each do |sensor| %>
      <tr>
        <td><%= sensor.name %></td>
        <td><%= link_to 'Show', sensor %></td>
        <td><%= link_to 'Edit', edit_sensor_path(sensor) %></td>
        <td><%= link_to 'Destroy', sensor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sensor', new_sensor_path %>

app/views/sensors/new.html.erb
<h1>New Sensor</h1>

<%= render 'form' %>

<%= link_to 'Back', sensors_path %>

app/views/sensors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sensor.name %>
</p>

<%= link_to 'Edit', edit_sensor_path(@sensor) %> |
<%= link_to 'Back', sensors_path %>